In [1]:
import pandas as pd

In [2]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc'
url = f'{prefix}/taxi_zone_lookup.csv'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv'

In [3]:
df = pd.read_csv(url)

In [4]:
df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [5]:
len(df)

265

In [6]:
print(df.dtypes)

LocationID      int64
Borough           str
Zone              str
service_zone      str
dtype: object

In [7]:
!uv add psycopg2-binary

Resolved 119 packages in 0.99ms
Checked 10 packages in 6ms

In [10]:
from sqlalchemy import create_engine
engine = create_engine("postgresql+psycopg2://postgres:postgres@localhost:5433/ny_taxi")

In [11]:
print(pd.io.sql.get_schema(df, name = 'taxi_zone_data', con=engine))

CREATE TABLE taxi_zone_data (
	"LocationID" BIGINT,
	"Borough" TEXT,
	"Zone" TEXT,
	service_zone TEXT
)

In [12]:
df.to_sql(name = 'taxi_zone_data', con=engine, if_exists='replace')

265

In [13]:
df

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                       NV          NaN
264         265        Unknown                      NaN          NaN

[265 rows x 4 columns]